In [2]:
# introduction to numpy ----->
# numpy is an open source library  that is used for scientifice calculation 
## why numpy is better than list !
##  1--> list hetrogenous data type and numpy is homogenous data typeabs 
## 2---> list take more space or memory as compair to numpy 
## 3---> list take time execution as compare to numpy

In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

In [9]:
a=[10,20,30,40]
type(a)

list

In [17]:
b=np.array(a)
type(b)

numpy.ndarray

## how can we create a user define array

In [24]:
a=[]
size=int(input("enter your size"))
for i in range(size):
    val =int(input("enter your number "))
    a.append(val)
print(a)
b=np.array(a)
b

enter your size 3
enter your number  1
enter your number  2
enter your number  3


[1, 2, 3]


array([1, 2, 3])

In [28]:
type(b)

numpy.ndarray

## how can we check shape and size and dimensional os array

In [35]:
a=[[1,2,3],[12,3,4],[5,5,4]]
b=np.array(a)
b

array([[ 1,  2,  3],
       [12,  3,  4],
       [ 5,  5,  4]])

In [43]:
print("total shape=",b.shape)## shape =n(row),n(col)

total shape= (3, 3)


In [45]:
print("total size ",b.size) ## size =n(rows) * n(col)

total size  9


In [51]:
# per-defined fuitnction in numpy

In [53]:
# (1).zeros () ----> it will return an array in which all the valles will be 0 in 
## either one -dimensional or multi-dimensional 

In [55]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [57]:
b=np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [63]:
print("total shape  =",a.shape)
print("total eliment",a.size)

total shape  = (3,)
total eliment 3


In [65]:
print("total shape  =",b.shape)
print("total eliment",b.size)

total shape  = (3, 3)
total eliment 9
