In [4]:
import numpy as np

In [6]:
a=np.array([1,2,35,5,5,654165,4])
a

array([     1,      2,     35,      5,      5, 654165,      4])

In [8]:
np.unique(a,return_index=True,return_counts=True)

(array([     1,      2,      4,      5,     35, 654165]),
 array([0, 1, 6, 3, 2, 5], dtype=int64),
 array([1, 1, 1, 2, 1, 1], dtype=int64))

In [10]:
# linespace () ----> it will create an array in which gap of values will be equal 
# syntax : np.linespace (min, max ,total_numbers)

In [14]:
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [16]:
## hstack -----> it will combined all the array in horizontally 
## vstack -----> it will combined all the array in vertically

In [18]:
a=np.array([1,2,3])
b=np.array([5,6,7,1])
c=np.array([9,10,11,1])


In [22]:
np.hstack((a,b,c))

array([ 1,  2,  3,  5,  6,  7,  1,  9, 10, 11,  1])

In [24]:
np.vstack((a,b,c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4